name: Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - run: bun install --frozen-lockfile

      - name: Create Release Pull Request or Publish
        uses: changesets/action@ce079ea084e08a340947ed4d6ecedb2433c8f293 # v1
        with:
          version: bun run version
          publish: bun run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTENSION_KEY_PEM: ${{ secrets.EXTENSION_KEY_PEM }}
          REQUIRE_CHROME_KEY: "1"
